### ISSUE TITLE
The Int63 library is confusing

### ISSUE THREAD

**Issue by lthms** [coq/coq#12109]
Dear Coq developers,

Native/primitive integers are a wonderful feature recently added to Coq. I start using them in projects of mine, and I have some feedback I would like to share with you. Of course, I don’t pretend I know the truth or anything. I am very open to discussing all of this.

#### Description of the problem

This is not a technical problem, but rather a discussion about certain choices that have been made with regards to the [`Int63`](https://coq.github.io/doc/master/stdlib/Coq.Numbers.Cyclic.Int63.Int63.html) library.

There are several things that I find bothering, and I guess this is a good time to bring that up.

1. `int` in Coq encodes *unsigned* integers, whereas `int` everywhere else in the world of programming languages encodes *signed* integers. This is really confusing to my opinion, and one good proof of that is, I think, reading the OCaml code implementing this, where one `int` type is equal to some `unit` type etc. From a naming perspective, I therefore believe `int` should be rename `uint` or something. 
2. Why 63 bits integers? I know that, in OCaml, primitive integers are 63 bits for a technical reason (unbox integers compatible with a garbage collector language); that being said, integers in Coq, even native integers, are not unbox. They always live at least in an ast of type `Constr.t`. So I am not sure we really benefit from having unboxed integers in this case. One may argue that 1 bit (especially when you have 64 bits in total) is not a big deal, but there are some situation where one may need to have 64 bits. For instance, if I want to implement a WebAssembly VM in Coq, which requires 64 bits integers, I cannot use `int` which feels like a loss! We could try to do some benchmark, but it feels like we could afford to use boxed, 64 bits integers for Coq to be less… OCaml-specific in this regards.
3. ~The notations are not consistent with the rest of the standard library. More specifically, `<` lives in `Prop` in the rest of the stdlib, but in `bool` for `int`.~

#### Coq Version

I believe the `Int63` module has not changed dramatically since primitive integers have been introduced.

**Comment by lthms** [comment]
For the sake of discussion, do you think it is a good idea if I try to address the first point of my list (using boxed, 64bits integers rather than unboxed, 63bits)?

**Comment by ppedrot** [comment]
cc @maximedenes

**Comment by lthms** [comment]
It looks like the third has been addressed, which in neat!

FTR, I have been able to implement signed integers using the `int` type: https://github.com/coq-community/coqffi/blob/main/theories/Data/Int.v

**Comment by proux01** [comment]
> native integers, are not unbox

@lthms Sorry for the late answer, that's not true fot the VM (`vm_compute`) nor for `native_compute`.

**Comment by lthms** [comment]
I admit I am less familiar with how both `vm_compute` and `native_compute` work, and I didn’t consider them submitting this issue. Thanks for the insight!

I am also glad to see the work of #13559 and will definitely keep an eye on it to give my 2cts if there is 2cts that are worth sharing.

**Comment by proux01** [comment]
Sure, any opinion is welcome. Currently, the big picture is:
* #13559 adds a `SInt63` module for signed integers, adding specific operations (signed comparisons and division, parser/printer for constants) a bit like your proposal but with primitive operations in the kernel (much more efficient than going through Z)
* `Ìnt63` could be "copied" as `Uint63` and deprecated
* in a few releases we could remove `Int63` and consider renaming `Sint63` to `Int63` or not (again with a deprecation phase)

**Comment by spitters** [comment]
It looks like unsigned 64 bit integers are still not available. Should we reopen this issue?
We have a use case for it here:
https://github.com/hacspec/hacspec/issues/63

**Comment by JasonGross** [comment]
> It looks like unsigned 64 bit integers are still not available. Should we reopen this issue? We have a use case for it here: [hacspec/hacspec#63](https://github.com/hacspec/hacspec/issues/63)

I think this issue is mostly not about 63 vs 64-bit integers.  Would you be fine with re-closing this issue and opening a new one specifically about 64-bit boxed integer support?  (This can be in addition to 63-bit support, allowing users to chose whether the performance of unboxing is more or less important than having full 64-bit integers)
