### ISSUE TITLE
[ssr] failure for `have` with `ltac:` in a notation

### ISSUE THREAD

**Issue by CohenCyril** [coq/coq#8190]
#### Version
The Coq Proof Assistant, version 8.8.1 (July 2018)
compiled on Jul 25 2018 17:35:15 with OCaml 4.06.0

#### Operating system
Linux 4.16.0-1-amd64 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux

#### Description of the problem

I do not understand why the following two uses of `have` do not give the same result...
(I expect both to succeed, like the second one, by generalizing over left evars)

```coq
Require Import ssreflect.

Notation zero := (ltac: (exact 0)).

Definition f (m n : nat) : nat := m.
Notation fzero m := (f zero m).

Lemma test : False.
Fail have := fzero _.
have := f zero _.
Abort.
```

The same problem happens when expanding the first notation inside the second:
```coq
Notation f_exact_zero m := (f (ltac: (exact 0)) m).

Lemma test : False.
Fail have := f_exact_zero _.
have := f (ltac: (exact 0)) _.
Abort.
```

@gares do you understand this?

**Comment by CohenCyril** [comment]
@maximedenes this is my problem...

**Comment by maximedenes** [comment]
A related issue:

```coq
Require Import ssreflect.
Notation foo := _.
Goal True.
have := foo.
```

produces a goal shown as `foo` (evar not generalized it seems).

**Comment by gares** [comment]
I think the notation is not affecting have...
```
Require Import ssreflect.
Notation foo := _ (only parsing).
Goal True.
have := foo.
```

**Comment by gares** [comment]
Notations are affecting tactic in terms:
```
Notation zero := (ltac: (exact 0)).
Definition f (m n : nat) : nat := m.
Notation fzero m := (f zero m).
Lemma test : False.
Fail eassert (H : fzero _ = 3). (* no space, notation with an indirect use of tac in terms *)
eassert (H : f zero _ = 3).
```

**Comment by gares** [comment]
The behavior is the following:
- if a term uses a notation with an `ltac:..` inside, things are fine (interp_open_constr evaluates the ltac code).
- if a term contains a notation that contains a notation with an `ltac:..` then the ltac code is not evaluated and the evar is let ther.

To me there are two bugs here:
- notations must, somehow, remove the "ltac decoration" from the `GHole` node (while being unraveled?)
- eassert complains about unresolved evars... shouln't it be ok with it?

**Comment by gares** [comment]
@CohenCyril could you update the first message of this PR with a pointer down here?

**Comment by gares** [comment]
My bet is that notations are stores as fully developed. Indeed the second notation emits a warning that it cannot be used for printing, since it contains some ltac code. It does not, but uses another notation that does. Maybe this inlining breaks the ltac-annotated `GHole`.

**Comment by CohenCyril** [comment]
The bug is affected by the presence of parameters in the notations, because this works:
```coq

Notation zero := (ltac: (exact 0)).
Definition f (m n : nat) : nat := m.
Notation fzero := (f zero).
Lemma test : False.
eassert (H : fzero = fun _ =>3).
```

**Comment by CohenCyril** [comment]
Actually, my bug happens ONLY with parameters, and when they are applied to holes when using the notation, cf third example in original post.

**Comment by gares** [comment]
One can reproduce the bug using `Check` so I removed the labels ltac and tactics

**Comment by gares** [comment]
The minimal example is
```coq
Notation zero := (ltac: (exact 0)).
Notation foo x := (x + zero).

(* Let's use foo, the offending notation with a parameter *)
Check foo 1.
Fail Check foo _. (* here I pass _ for the parameter *)

(* Now I get rid of `foo` and do the unfolding by hand *)
Check (1 + zero).
Check (_ + zero).
```

**Comment by herbelin** [comment]
Hi, the problem seems to be a bit tricky. The notation (roughly) generates the following Ltac code:
```coq
Check ltac:(let x := (eval cbn in _) in exact 0).
```
which indeed fails. (Note: it should be an identity conversion rather than `cbn` but I don't know how to express this in the syntax.)

Ideally, one should generate instead the code
```coq
Check ltac:(let a := open_constr:(_) in exact a).
```
internally using a `TacGeneric` with the appropriate tag. This is in `Tacintern.notation_subst`. Don't hesitate to give it a try, that would be wonderful.

**Comment by gares** [comment]
I must confess I do not understand your message at all, and I don't have time to learn this part of the system I've never looked at. Please just confirm I've assigned the bug to the right persons.

**Comment by CohenCyril** [comment]
> When there is an `ltac:(tactic dependent on some arguments)`
Hi Hugo, it seems to me that in the example `Notation zero := (ltac: (exact 0)).` there is no argument in the tactic. Where does your `let x := (eval cbn in _) in` come from in your example?

**Comment by herbelin** [comment]
@cohencyril: What matters in the example is the argument to `foo` when `foo x` expands to `x + ltac: (exact 0)`. Doing an analysis of variables which occur effectively would indeed be another direction to fix this issue, since, here `ltac: (exact 0)` does not depend on `x`. But it would not fix e.g.:
```
Notation foo x := (1 + ltac:(exact (@id x 1))).
Check foo _.
```
I've seen examples where collecting ltac variables which effectively occur could be useful. So, both directions (i.e. moving the constr's passed to ltac to open_constr's _and_ avoiding passing the arguments which do not occur) are indeed worth.

**Comment by CohenCyril** [comment]
@herbelin oh ok, I think I understand now!

**Comment by CohenCyril** [comment]
@herbelin I played a little bit to understand where the `cbn` happened and I do not find it. The code you mention uses
```ocaml
let c = ConstrMayEval (ConstrTerm c) in [...]
```
and not something like
```ocaml
let cbn = Cbn {rBeta = true; rMatch = true; rFix = true; rCofix = true;
                   rZeta = true; rDelta = true; rConst = []} in
let c = ConstrMayEval (ConstrEval (cbn, c)) in [...]

**Comment by CohenCyril** [comment]
@herbelin the exact code you gave fixed my problem. I still do not understand what the identity conversion (`ConstrMayEval (ConstrTerm c)`) is supposed to do compared to `TacGeneric (Genarg.in_gen (Genarg.glbwit Stdarg.wit_open_constr) c)` and whether there should also be a primitive for the latter, but I'm submitting a pull request #8200 and people can discuss it there, I suppose...

**Comment by herbelin** [comment]
> I still do not understand what the identity conversion (ConstrMayEval (ConstrTerm c)) is supposed to do compared to TacGeneric (Genarg.in_gen (Genarg.glbwit Stdarg.wit_open_constr) c) and whether there should also be a primitive for the latter, but I'm submitting a pull request #8200 and people can discuss it there, I suppose...

This is a very good question. Using `ConstrMayEval (ConstrTerm c)` fails because its interpretation function `Tacinterp.interp_constr_may_eval` interprets `c` with the function `interp_constr` and this latter function checks that all holes are resolved. This means that another fix could be to change instead the interpretation function for `ConstrMayEval (ConstrTerm c)` to `interp_open_constr` (or `interp_open_constr_with_classes`).

Doing this change would have a bigger impact than just in `ltac:(...)` subterms of a notation. It would have the effect e.g. that
```
Goal nat.
let x := eval cbn in _ in exact (@id x 0).
```
works, while, currently, it fails with `Cannot infer an internal placeholder of type "Type".`. I'm not experienced enough in tactic programming to evaluate which semantics is better (if ever one is uniformly better, and if the `open_constr` one, with type classes or not). Maybe @JasonGross has an opinion.

**Comment by JasonGross** [comment]
Where is `ConstrMayEval (ConstrTerm c)` used, currently?  I suspect I would have an opinion, if I knew the scope of what this change would do.

(However, I believe that The Correct thing to do, given the current scope of notations, is interpret binders as `ident` and non-binders as `uconstr`, for `Notation`.)

**Comment by maximedenes** [comment]
@CohenCyril did you have some code that fixed this issue? Was it ever submitted as a PR?

**Comment by JasonGross** [comment]
There is code at https://github.com/coq/coq/pull/8200 It stalled for lack of a good option.  In particular:
- if we pass in terms as uconstr, then in order to, e.g., match on the variable, you need to first wrap it in constr:(...) (backwards incompatibly)
- if we pass in variables as open_constr, then typeclasses are not resolved, holes from unused variables stick around as evars, etc
- if we pass in variables as constr, then we run into the current problems

I think the ideal design is using uconstr (or preterm in Ltac2?), and having automatic coercions from uconstr to constr, but this is probably too invasive a change to make for Ltac1, and goes in the wrong direction for Ltac2.

**Comment by ppedrot** [comment]
IIRC in Ltac2 the problem is already solved since you get a `preterm` in the notation expansion. So you can do whatever you want with it (in theory, no pretyping knobs are exported currently).

**Comment by SkySkimmer** [comment]
Leaving this as won'tfix for ltac1
