### ISSUE TITLE
Repository tags are missing / wrong

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#8543]
As of the time of submission of this bug `git describe` gives us:
```
V8.8+alpha-4073-g5764e978a
```
which is plain wrong. Please fix the tags.

**Comment by Zimmi48** [comment]
I'm not sure the blocker label is relevant here, especially as it can perfectly be fixed at any time *after* a release. We should also start looking for a RM for 8.10 BTW.

**Comment by ejgallego** [comment]
The blocker label is like 110% percent relevant, for git master is still 8.8+alpha!

**Comment by Zimmi48** [comment]
You missed my point (or you ignored it).

**Comment by ejgallego** [comment]
I did not, the branch cannot just be in the state it is, specially when the beta is announced.

**Comment by ejgallego** [comment]
I've added https://github.com/coq/coq/releases/tag/V8.10%2Balpha to point to https://github.com/coq/coq/commit/f61ee79e4a6db070e3bf26f76e8bdb42b85c3a72 as suggested by @Zimmi48 ; however, we are missing the `V8.9+alpha` tag, thus marking this bug not fixed yet.

**Comment by Zimmi48** [comment]
See also the discussion that happened in #7008.

**Comment by ejgallego** [comment]
Well, the discussion didn't converge, so indeed I propose we continue with the current scheme and thus close #8543 adding a v8.9+alpha tag for bc0fa22.

I will add the tag in a few days unless somebody opposes.

**Comment by Zimmi48** [comment]
Ouch! Yes, there is a problem: you used a small `v` instead of a capital `V` (and you didn't sign the tag).

**Comment by Zimmi48** [comment]
Sorry I should have noticed that the name was wrong from your previous message.

**Comment by ejgallego** [comment]
Ups; not so familiar with this stuff. New and signed tag pushed, proceeding to delete the wrong one.
